r3bl-org/r3bl-open-core

src/lib.rs, src/tree_memory_arena/arena.rs, src/tree_memory_arena/mt_arena.rs, src/tui/mod.rs, src/utils/safe_unwrap.rs
It is good practice to use enforce Clippy's suggestions and the usage of 2018 idioms as warnings. Why not errors? During development, it is nice to be able to iterate without caring about Clippy. 
Also removed is the usage of deprecated 2018 hidden lifetimes. It also seems like the external crate export was unused.
=> Warn on clippy and usage of rust 2018 idoms.

tuify/examples/main_interactive.rs, tuify/src/components/apply_style_macro.rs, tuify/src/components/mod.rs, tuify/src/components/select_component.rs, tuify/src/components/style.rs, tuify/src/main.rs, tuify/src/public_api.rs
AddStylingSupportSoThatSelectedAndUnselectedStylesCanBePassedIn
===
- resolves #116 
- Add `Style` struct and updates `SelectComponent` to make use of it.
Accepts fields for:
- Foreground color: Color
- Background color: Color
- Bold: bool
- Italic: bool
- Dim: bool
- Underline: bool
- Reverse: bool
- Strikethrough: bool
- Has following fields:
- normal_style:
- Default just takes what was already in `SelectComponent` and moves it here. 
- selected_style
- Default is the same as normal style with swapped foreground/background colors. 
- header_style
- Default just takes what was already in `SelectComponent` and moves it here. 
- Declarative macro.
- Handles generating the inputs for the `queue!` macro used in `SelectComponent`.
- Has pattern for each of the above styles.
- Generates …
=> AddStylingSupportSoThatSelectedAndUnselectedStylesCanBePassedIn

ansi_color/README.md, ansi_color/src/lib.rs, core/Cargo.toml, core/src/tui_core/styles/tui_color.rs, deny.toml, tui/Cargo.toml
=> Audit crates

core/Cargo.toml, core/README.md, core/src/decl_macros.rs, deny.toml
Remove the use of `reqwest` crate from the core code. Since the `encoding-rs` was dependent on the reqwest code and we were expecting an license exception for `enoding-rs`. But now we don't have reqwest, thus there is no encoding-rs in dependencies and can be safely removed from license exception.
Closes #140
=> [core] remove `reqwest` and license exception `encoding-rs`

tui/Cargo.toml, tui/src/tui/editor/editor_buffer/editor_buffer_clipboard_support.rs, tui/src/tui/editor/editor_buffer/editor_buffer_struct.rs, tui/src/tui/editor/editor_buffer/mod.rs, tui/src/tui/editor/editor_component/editor_event.rs, tui/src/tui/editor/editor_engine/editor_engine_internal_api.rs
The PR comprises of changes required to implement the feature where we can copy the text to the clipboard from TUI. Here, We set in a logic which takes whole text and the `SelectionMap`. We then take the RowIndex in order and then based on it extract the selection caret values from all the lines(rows). Then we pass this to clipboard crate API to copy with our system clipboard.
Another minor change which have been made is for `get_as_string()` method for SelectionMap is now using join delimeter as a newline instead of comma.
The same text as seen in the image gets selected to the clipboard.
Closes #147
=> [tui] feature : Copy Selected text in TUI

tuify/README.md, tuify/src/lib.rs
Multiple selection is implemented in https://github.com/r3bl-org/r3bl_rs_utils/pull/132. Remove the outdated information in the document.
=> remove outdated information because multiple selection has been implemented.

run.nu, tui/Cargo.toml, tui/examples/demo/ex_editor/app.rs, tui/examples/demo/ex_editor/launcher.rs, tui/examples/demo/ex_pitch/app.rs, tui/examples/demo/ex_pitch/launcher.rs, tui/examples/demo/ex_rc/app.rs, tui/examples/demo/ex_rc/launcher.rs, tui/src/lib.rs, tui/src/tui/dialog/dialog_component/dialog_event.rs, tui/src/tui/editor/editor_component/editor_event.rs, tui/src/tui/terminal_lib_backends/keypress.rs, tui/src/tui/terminal_lib_backends/modifier_keys_mask.rs, tui/src/tui/terminal_lib_backends/test_input_event.rs, tui/src/tui/terminal_lib_backends/test_keypress.rs, tui/src/tui/terminal_lib_backends/test_mouse_input.rs
The latest bitflags crate breaks things for modifier_keys_mask.rs.
So drop this depenedency so that Cargo.toml can be upgraded to the
latest of each dep.
Fixes: #161
=> [tui] Remove bitflags dep, so Cargo.toml can be upgraded to latest

tui/examples/demo/ex_editor/app.rs, tui/examples/demo/ex_editor/launcher.rs, tui/examples/demo/ex_pitch/app.rs, tui/examples/demo/ex_pitch/launcher.rs, tui/examples/demo/ex_rc/app.rs, tui/examples/demo/ex_rc/launcher.rs, tui/src/tui/editor/editor_buffer/editor_buffer_clipboard_support.rs, tui/src/tui/editor/editor_buffer/selection_map.rs, tui/src/tui/editor/editor_component/editor_event.rs, tui/src/tui/editor/editor_engine/editor_engine_internal_api.rs
Make all the tui examples use "Ctrl + q" for exit, since "Ctrl + x" is now used for Cut.
Fixes: #144
=> [tui] Add cut selected text support in editor component

core/src/decl_macros.rs, tui/examples/demo/ex_app_no_layout/app_main.rs, tui/examples/demo/ex_app_with_1col_layout/single_column_component.rs, tui/examples/demo/ex_app_with_2col_layout/column_render_component.rs, tui/examples/demo/ex_editor/app_main.rs, tui/examples/demo/ex_pitch/app_main.rs, tui/examples/demo/ex_rc/app_main.rs, tuify/examples/main_interactive.rs
With these changes, We are introducing a new macro called `send_signal!` which will take in the sender and the event. This will make code more clean by removal of repeated tokio spawn blocks.
Closes #219
=> [tui] Adding macro to perform mpsc signal sending

CHANGELOG.md, README.md, tui/src/tui/editor/editor_engine/editor_engine_api.rs, tui/src/tui/md_parser/block/parse_block_heading.rs, tui/src/tui/md_parser/block/parse_block_markdown_text_until_eol.rs, tui/src/tui/md_parser/parse_element.rs, tui/src/tui/md_parser/parser.rs, tui/src/tui/mod.rs, tui/src/tui/syntax_highlighting/md_parser_syn_hi/md_parser_syn_hi_impl.rs
- Remove use of syntect parser and syntax highlighter. This can be enabled by changing a bool const in tui/src/tui/mod.rs
Fixes: #253
=> Rewrite MD Parser and change how headings and plain text is handled

tui/src/tui/editor/editor_engine/editor_engine_internal_api.rs
- closes #261 
- Movement from current line to previous line during selection using the left arrow key was resulting in previous line being selected in its entirety.
- The PR does not include test-cases for the same as those are currently being targeted as part of a larger effort to have better test-cases for editor #184 and would be added in upcoming PRs.
=> [tui][edi] Fix incorrect selection on moving to previous line

CHANGELOG.md, tuify/src/components/select_component.rs, tuify/src/event_loop.rs, tuify/src/keypress.rs, tuify/src/lib.rs, tuify/src/public_api.rs, tuify/src/test_utils.rs
Add ability to test read from stdin. Provide wrapper for crossterm read() and also test mock that simulates KeyPresses.
Support for write and stdout mocking is already present.
=> [tuify] Add tests to select_from_list()

CHANGELOG.md, tui/src/tui/dialog/dialog_engine/dialog_engine_api.rs, tui/src/tui/editor/editor_component/editor_event.rs, tui/src/tui/editor/editor_engine/editor_engine_api.rs, tui/src/tui/editor/editor_engine/editor_engine_internal_api.rs, tui/src/tui/editor/test_editor.rs
- <kbd>Escape</kbd> key now clears the selection.
- <kbd>Ctrl+A</kbd> now selects all text.
- Tests for the items above.
=> [tui] Add editor component text selection features

cmdr/src/bin/giti.rs, cmdr/src/giti/branch/delete.rs, cmdr/src/giti/branch/giti_ui_templates.rs, cmdr/src/giti/mod.rs, tuify/README.md, tuify/src/lib.rs
Now `giti branch delete` uses `select_from_list_with_multi_line_header` function insead of a single line header `select_from_list`.
=> [giti] Update giti to use multi line header component

ansi_color/Cargo.toml, ansi_color/src/color.rs
For issue #135
The tests added use test_case macro to easily generate many test for various colors.  What the test lack is edge cases or negative tests.  These can be easily added using the test_case format.  I could use some feedback and suggestions on the tests.
=> Add tests for existing ansi_color

cmdr/src/bin/giti.rs, cmdr/src/color_constants.rs, cmdr/src/giti/branch/checkout.rs, cmdr/src/giti/branch/delete.rs, cmdr/src/giti/clap_config.rs, cmdr/src/giti/ui_strings.rs
Closes #303
User can type in a branch name as 4th command line argument and if the branch name is valid, then user switched to the branch. 
In case branch name is invalid, user will see an error message.
In case user has modified files on branch and they try to checkout another branch, user will see a message saying to stash or commit the current changes before changing branches. 
If user has more than one modified files that need to be committed or stashed.
=> [giti] Handle `giti branch checkout` modified files use case

CHANGELOG.md, Cargo.lock, docs/release-guide.md, terminal_async/Cargo.toml, terminal_async/examples/spinner.rs, terminal_async/examples/terminal_async.rs, terminal_async/src/lib.rs, terminal_async/src/public_api/spinner.rs, terminal_async/src/public_api/terminal_async.rs, terminal_async/src/readline_impl/history.rs, terminal_async/src/readline_impl/line.rs, terminal_async/src/readline_impl/readline.rs, terminal_async/src/spinner_impl/spinner_render.rs
[terminal_async] Remove use of TokioMutex
There are some dangers to being "cancel safe" when using async Rust.
This can be seen in the links below (to docs, and video) which outline
what the problem is.
https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html
https://www.youtube.com/watch?v=1zOd52_tUWg&t=2088s
It is better to avoid using a TokioMutex to check for cancellation
and instead to use broadcast channel for shutdown signals, just like
the code already does. The changes made in this commit are related
to removing the use of TokioMutex all together in favor of the StdMutex
since there is really no need to use it at all. And thus avoid any
potential of "cancel safe" errors cropping up!
=> v0.4.0-terminal_async

.vscode/settings.json, core/src/utils/debug_file_logging.rs, simple_logger/src/lib.rs, terminal_async/README.md, terminal_async/examples/terminal_async.rs, terminal_async/src/lib.rs, terminal_async/src/public_api/spinner.rs, terminal_async/src/public_api/terminal_async.rs, terminal_async/src/readline_impl/line.rs, terminal_async/src/readline_impl/readline.rs, terminal_async/src/readline_impl/shared_writer.rs
[core]
- Add new function in debug_file_log() for quick debugging
[terminal_async]
- Make it simple to use TerminalAsync and Readline, so that
simply dropping Readline is sufficient to shut everything
down.
- You can look at the examples/terminal_async.rs to see how
this works.
=> [terminal_async, core] Clean up lifecycle

core/src/tui_core/color_wheel/color_wheel_impl.rs, core/src/tui_core/color_wheel/lolcat_impl.rs, core/src/tui_core/graphemes/gc_string.rs, tui/examples/demo/ex_pitch/app_main.rs, tui/examples/demo/ex_pitch/state.rs, tui/examples/demo/ex_rc/app_main.rs, tui/examples/demo/ex_rc/state.rs, tui/src/tui/editor/editor_component/editor_component_struct.rs, tui/src/tui/syntax_highlighting/intermediate_types.rs, tui/src/tui/terminal_lib_backends/render_pipeline_to_offscreen_buffer.rs
Introduce a simple iterator for GCString that yields logical string segments, simplifying indexing operations. Fix the AST cache regression affecting the demo examples, ensuring that Ctrl+P and Ctrl+N function correctly to render new data.
Fixes #392, #394
=> Implement GCString iterator and fix AST cache regression in demos

cmdr/src/analytics_client/ui_str.rs, cmdr/src/common/ui_templates.rs, cmdr/src/giti/branch/branch_delete_command.rs, done.md, todo.md, tui/src/core/ansi/ansi_styled_text.rs, tui/src/core/tui_core/spinner_impl/spinner_render.rs, tui/src/readline_async/mod.rs, tui/src/readline_async/readline_async_api.rs
Also audit the following:
- tui/src/core/tui_core/spinner_impl/spinner_render.rs, render_tick(),
- tui/src/readline_async/readline_async_api.rs, try_new(),
to ensure that they can handle spinner message and readline_async prompt
that can contain ANSI escape sequence text.
These can both handle ANSI escape sequences in the spinner message and
prompt.
Fixes: #420
=> [tui] Add clip() and convert() to ASText and clean up naming
