r3bl-org/r3bl-open-core

- core/src/tui_core/styles/stylesheet.rs
- macro/src/make_style/codegen.rs
- src/tui/mod.rs
- src/utils/mod.rs
- tests/test_make_style_macro.rs
- tests/test_style.rs
- tests/test_tw_surface.rs
There are some other minor changes which involved addition of space (intellij automatically formats files so the margin contains multiples of 4 spaces)
> Fixed issues relating to DSL

- src/tui/crossterm_helpers/tw_input_event.rs
> Replace Size with size!

- tui/README.md
- tuify/src/components/select_component.rs
- tuify/src/public_api.rs
- tuify/src/state.rs
Fixed : #133 
- replaced '>' with nice ANSI symbol for better UI experience to user
> Add ANSI symbol instead of ">" for row selection

- tuify/Cargo.toml
- tuify/examples/main_interactive.rs
- tuify/src/components/select_component.rs
- tuify/src/public_api.rs
- tuify/src/scroll.rs
- Add tests
- Rewrite logic to detect location of caret in viewport
- Add better demo / example
- Improve rendering of multi select items (don't show index)
- Bump version number for tuify to 0.1.14
Fixes: #143
> [tuify] Fix bug causing render crashes

- ansi_color/src/ansi_escape_codes.rs
---
#127 ([ansi_color] Add comprehensive tests for SGR codes #127)
---
---
> Added comprehensive tests for SGR codes

- ansi_color/src/detect_color_support.rs
---
#126 ([ansi_color] Remove all the arc<mutex<_>> & replace w/ unsafe)
---
---
> [ansi_color] Replaced Arc<Mutex<_>> w/ unsafe

- .github/workflows/rust.yml
- run.nu
- tuify/Cargo.toml
- tuify/src/components/select_component.rs
https://github.com/r3bl-org/r3bl_rs_utils/issues/154
> [all] Setup github actions

- core/src/color_text.rs
- tui/src/tui/editor/editor_buffer/editor_buffer_struct.rs
- tui/src/tui/editor/editor_buffer/selection_map.rs
- tui/src/tui/editor/editor_component/editor_event.rs
- tui/src/tui/editor/editor_engine/editor_engine_internal_api.rs
> [tui] Add backspace support to selection in editor component

- tuify/README.md
- tuify/examples/main_interactive.rs
- tuify/src/lib.rs
- Add tuify single select as a way to run examples
- Update README and lib.rs with information about `giti`
https://github.com/r3bl-org/r3bl-open-core/assets/22040032/accbd5e5-a997-4bf2-a118-080512e5d701
> Add tuify single select as a way to run examples

- tui/examples/demo/ex_app_with_1col_layout/app_main.rs
- tui/examples/demo/ex_app_with_2col_layout/app_main.rs
- tui/examples/demo/ex_pitch/app_main.rs
- tui/src/tui/dialog/dialog_component/dialog_component_struct.rs
Fixes the following TUI examples :
- #211 
- #212
- #213
- #214
> [tui][example] Fixes examples

- tuify/src/bin/giti.rs
> [tuify][giti] Fix the subcommand issue w/ clap

- tuify/README.md
- tuify/examples/main_interactive.rs
- tuify/examples/single_select_quiz_game.rs
- tuify/src/components/select_component.rs
- tuify/src/components/style.rs
- tuify/src/lib.rs
> 224-tuify-update-the-tuify-default-design

- run.nu
- tui/run.nu
Top level run.nu runs global actions (like run.nu all)
The tui/run.nu runs tui specific actions (like run.nu log)
> [all][tui] Clean up run.nu

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/contributing_guides/BRANCH.md
- docs/contributing_guides/COMMIT_MESSAGE.md
- docs/contributing_guides/ISSUE.md
- docs/contributing_guides/PULL_REQUEST.md
- docs/contributing_guides/STYLE_GUIDE.md
> Update contributing guides

- tui/src/tui/dialog/dialog_engine/dialog_engine_api.rs
- tui/src/tui/editor/editor_buffer/editor_buffer_struct.rs
- tui/src/tui/editor/editor_component/editor_component_struct.rs
- tui/src/tui/editor/editor_engine/editor_engine_api.rs
- tui/src/tui/terminal_lib_backends/render_op.rs
> [tui] Editor component - cache content to avoid rendering if unmodified

- cmdr/src/giti/branch/delete.rs
- tuify/README.md
- tuify/examples/main_interactive.rs
- tuify/examples/single_select_quiz_game.rs
- tuify/src/bin/rt.rs
- tuify/src/components/select_component.rs
- tuify/src/public_api.rs
- tuify/src/react.rs
- tuify/src/state.rs
- tuify/src/term.rs
Closes #264
- Created a new api for component which has multi line header called `select_from_list_with_multi_line_header`.
- Updated docs.
- Updated tests.
> [tuify] Create a multi line header component

- cmdr/README.md
- cmdr/src/bin/edi.rs
- cmdr/src/bin/giti.rs
- cmdr/src/color_constants.rs
- cmdr/src/giti/branch/checkout.rs
- cmdr/src/giti/branch/delete.rs
- cmdr/src/giti/branch/giti_ui_templates.rs
- cmdr/src/giti/clap_config.rs
- cmdr/src/giti/common_types.rs
- cmdr/src/giti/mod.rs
- cmdr/src/giti/ui_strings.rs
- cmdr/src/lib.rs
- tuify/src/components/select_component.rs
- tuify/src/constants.rs
> [giti] Build `giti branch checkout` UX

- CHANGELOG.md
- Cargo.lock
- docs/release-guide.md
- terminal_async/Cargo.toml
- terminal_async/examples/terminal_async.rs
- terminal_async/src/public_api/tracing_setup.rs
> v0.5.2-terminal_async

- CHANGELOG.md
- tui/src/tui/terminal_window/main_event_loop.rs
> [tui] Refactor main_event_loop.rs to fix shutdown signal bug

- ansi_color/README.md
Update link to new location of `main.rs`
> Fix broken example link

- CHANGELOG.md
- tui/src/tui/editor/editor_buffer/buffer_struct.rs
- tui/src/tui/editor/editor_buffer/render_cache.rs
- tui/src/tui/editor/editor_engine/engine_public_api.rs
- tui/src/tui/editor/editor_engine/engine_struct.rs
- **[tui] Clean up RenderCache logic**
- **[tui] Clean up docs for buffer_struct.rs and engine_struct.rs**
- **[tui] Add AST in EditorEngine for huge performance win in editor**
> move rendercache
